server:
  port: 8080
spring:
  main:
    banner-mode: 'off' 
  jmx:
    enabled: true
  session:
    store-type: none
infinispan:
  remote:
    enabled: 'true'
    server-list: 127.0.0.1:11222
    use-auth: true
    auth-username: developer
    auth-password: dIRs5cAAsHIeeRIL
    auth-realm: default
    sasl-mechanism: DIGEST-MD5
    java-serial-whitelist: .*
#    marshaller: org.infinispan.commons.marshall.StringMarshaller



