server:
  port: 8080
spring:
  main:
    banner-mode: 'off'
  mvc:
    favicon:
      enabled: false
    jmx:
      enabled: true
  session:
    store-type: none
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
logging:
  level:
    org:
      jgroups:
        protocols: WARN